name: Tests

on:
  push:
    branches: [ main ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Package
        run: pip install -e .[test]

      - name: Clone Omi Data
        run: git clone --depth=1 https://github.com/Open-Markets-Initiative/omi-data-packets.git

      - name: Run Tests
        run: pytest -v


